CREATE TABLE IF NOT EXISTS checklist_inspecao (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    data_realizacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    placa VARCHAR(10) NOT NULL,
    km_inicial INTEGER NOT NULL,
    nivel_combustivel VARCHAR(10) NOT NULL,
    foto_km_inicial TEXT,
    foto_combustivel TEXT,
    foto_painel TEXT,
    motor_agua_radiador VARCHAR(10),
    motor_agua_radiador_foto TEXT,
    motor_agua_parabrisa VARCHAR(10),
    motor_agua_parabrisa_foto TEXT,
    motor_fluido_freio VARCHAR(10),
    motor_fluido_freio_foto TEXT,
    motor_nivel_oleo VARCHAR(10),
    motor_nivel_oleo_foto TEXT,
    motor_tampa_reservatorio VARCHAR(10),
    motor_tampa_reservatorio_foto TEXT,
    motor_tampa_radiador VARCHAR(10),
    motor_tampa_radiador_foto TEXT,
    limpeza_interna VARCHAR(20),
    limpeza_interna_foto TEXT,
    limpeza_externa VARCHAR(20),
    limpeza_externa_foto TEXT,
    foto_frontal TEXT,
    foto_traseira TEXT,
    foto_lateral_direita TEXT,
    foto_lateral_esquerda TEXT,
    pneu_dianteira_direita VARCHAR(10),
    pneu_dianteira_direita_foto TEXT,
    pneu_dianteira_esquerda VARCHAR(10),
    pneu_dianteira_esquerda_foto TEXT,
    pneu_traseira_direita VARCHAR(10),
    pneu_traseira_direita_foto TEXT,
    pneu_traseira_esquerda VARCHAR(10),
    pneu_traseira_esquerda_foto TEXT,
    pneu_estepe VARCHAR(10),
    pneu_estepe_foto TEXT
);

CREATE INDEX IF NOT EXISTS idx_placa ON checklist_inspecao(placa);
CREATE INDEX IF NOT EXISTS idx_data ON checklist_inspecao(data_realizacao);
CREATE INDEX IF NOT EXISTS idx_placa_data ON checklist_inspecao(placa, data_realizacao);
